version: "3.9"

services:
  gcloud:
    image: google/cloud-sdk:405.0.1-slim
    volumes:
      - gcp-creds:/creds
      - .:/app
    working_dir: /app
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds:
